/*
 * This file is generated by jOOQ.
 */
package org.opendatakit.briefcase.jooq;


import org.jooq.Sequence;
import org.jooq.impl.SequenceImpl;


/**
 * Convenience access to all sequences in PUBLIC
 */
@SuppressWarnings({"all", "unchecked", "rawtypes"})
public class Sequences {

  /**
   * The sequence <code>PUBLIC.FORM_METADATA_ID_SEQ</code>
   */
  public static final Sequence<Integer> FORM_METADATA_ID_SEQ = new SequenceImpl<Integer>("FORM_METADATA_ID_SEQ", Public.PUBLIC, org.jooq.impl.SQLDataType.INTEGER);
}
