/*
 * This file is generated by jOOQ.
 */
package org.opendatakit.briefcase.jooq;


import org.opendatakit.briefcase.jooq.tables.FormMetadata;


/**
 * Convenience access to all tables in PUBLIC
 */
@SuppressWarnings({"all", "unchecked", "rawtypes"})
public class Tables {

  /**
   * The table <code>PUBLIC.FORM_METADATA</code>.
   */
  public static final FormMetadata FORM_METADATA = org.opendatakit.briefcase.jooq.tables.FormMetadata.FORM_METADATA;
}
