/*
 * This file is generated by jOOQ.
 */
package org.opendatakit.briefcase.reused.db.jooq.tables.records;


import java.time.OffsetDateTime;
import org.jooq.Field;
import org.jooq.Record13;
import org.jooq.Record2;
import org.jooq.Row13;
import org.jooq.impl.UpdatableRecordImpl;
import org.opendatakit.briefcase.reused.db.jooq.tables.FormMetadata;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({"all", "unchecked", "rawtypes"})
public class FormMetadataRecord extends UpdatableRecordImpl<FormMetadataRecord> implements Record13<String, String, String, String, String, String, Boolean, String, String, OffsetDateTime, OffsetDateTime, String, String> {

  private static final long serialVersionUID = -1011526472;

  /**
   * Setter for <code>PUBLIC.FORM_METADATA.FORM_ID</code>.
   */
  public void setFormId(String value) {
    set(0, value);
  }

  /**
   * Getter for <code>PUBLIC.FORM_METADATA.FORM_ID</code>.
   */
  public String getFormId() {
    return (String) get(0);
  }

  /**
   * Setter for <code>PUBLIC.FORM_METADATA.FORM_VERSION</code>.
   */
  public void setFormVersion(String value) {
    set(1, value);
  }

  /**
   * Getter for <code>PUBLIC.FORM_METADATA.FORM_VERSION</code>.
   */
  public String getFormVersion() {
    return (String) get(1);
  }

  /**
   * Setter for <code>PUBLIC.FORM_METADATA.FORM_NAME</code>.
   */
  public void setFormName(String value) {
    set(2, value);
  }

  /**
   * Getter for <code>PUBLIC.FORM_METADATA.FORM_NAME</code>.
   */
  public String getFormName() {
    return (String) get(2);
  }

  /**
   * Setter for <code>PUBLIC.FORM_METADATA.FORM_FILE</code>.
   */
  public void setFormFile(String value) {
    set(3, value);
  }

  /**
   * Getter for <code>PUBLIC.FORM_METADATA.FORM_FILE</code>.
   */
  public String getFormFile() {
    return (String) get(3);
  }

  /**
   * Setter for <code>PUBLIC.FORM_METADATA.CURSOR_TYPE</code>.
   */
  public void setCursorType(String value) {
    set(4, value);
  }

  /**
   * Getter for <code>PUBLIC.FORM_METADATA.CURSOR_TYPE</code>.
   */
  public String getCursorType() {
    return (String) get(4);
  }

  /**
   * Setter for <code>PUBLIC.FORM_METADATA.CURSOR_VALUE</code>.
   */
  public void setCursorValue(String value) {
    set(5, value);
  }

  /**
   * Getter for <code>PUBLIC.FORM_METADATA.CURSOR_VALUE</code>.
   */
  public String getCursorValue() {
    return (String) get(5);
  }

  /**
   * Setter for <code>PUBLIC.FORM_METADATA.IS_ENCRYPTED</code>.
   */
  public void setIsEncrypted(Boolean value) {
    set(6, value);
  }

  /**
   * Getter for <code>PUBLIC.FORM_METADATA.IS_ENCRYPTED</code>.
   */
  public Boolean getIsEncrypted() {
    return (Boolean) get(6);
  }

  /**
   * Setter for <code>PUBLIC.FORM_METADATA.URL_MANIFEST</code>.
   */
  public void setUrlManifest(String value) {
    set(7, value);
  }

  /**
   * Getter for <code>PUBLIC.FORM_METADATA.URL_MANIFEST</code>.
   */
  public String getUrlManifest() {
    return (String) get(7);
  }

  /**
   * Setter for <code>PUBLIC.FORM_METADATA.URL_DOWNLOAD</code>.
   */
  public void setUrlDownload(String value) {
    set(8, value);
  }

  /**
   * Getter for <code>PUBLIC.FORM_METADATA.URL_DOWNLOAD</code>.
   */
  public String getUrlDownload() {
    return (String) get(8);
  }

  /**
   * Setter for <code>PUBLIC.FORM_METADATA.LAST_EXPORTED_DATE_TIME</code>.
   */
  public void setLastExportedDateTime(OffsetDateTime value) {
    set(9, value);
  }

  /**
   * Getter for <code>PUBLIC.FORM_METADATA.LAST_EXPORTED_DATE_TIME</code>.
   */
  public OffsetDateTime getLastExportedDateTime() {
    return (OffsetDateTime) get(9);
  }

  /**
   * Setter for <code>PUBLIC.FORM_METADATA.LAST_EXPORTED_SUBMISSION_DATE_TIME</code>.
   */
  public void setLastExportedSubmissionDateTime(OffsetDateTime value) {
    set(10, value);
  }

  /**
   * Getter for <code>PUBLIC.FORM_METADATA.LAST_EXPORTED_SUBMISSION_DATE_TIME</code>.
   */
  public OffsetDateTime getLastExportedSubmissionDateTime() {
    return (OffsetDateTime) get(10);
  }

  /**
   * Setter for <code>PUBLIC.FORM_METADATA.PULL_SOURCE</code>.
   */
  public void setPullSource(String value) {
    set(11, value);
  }

  /**
   * Getter for <code>PUBLIC.FORM_METADATA.PULL_SOURCE</code>.
   */
  public String getPullSource() {
    return (String) get(11);
  }

  /**
   * Setter for <code>PUBLIC.FORM_METADATA.EXPORT_CONFIGURATION</code>.
   */
  public void setExportConfiguration(String value) {
    set(12, value);
  }

  /**
   * Getter for <code>PUBLIC.FORM_METADATA.EXPORT_CONFIGURATION</code>.
   */
  public String getExportConfiguration() {
    return (String) get(12);
  }

  // -------------------------------------------------------------------------
  // Primary key information
  // -------------------------------------------------------------------------

  /**
   * {@inheritDoc}
   */
  @Override
  public Record2<String, String> key() {
    return (Record2) super.key();
  }

  // -------------------------------------------------------------------------
  // Record13 type implementation
  // -------------------------------------------------------------------------

  /**
   * {@inheritDoc}
   */
  @Override
  public Row13<String, String, String, String, String, String, Boolean, String, String, OffsetDateTime, OffsetDateTime, String, String> fieldsRow() {
    return (Row13) super.fieldsRow();
  }

  /**
   * {@inheritDoc}
   */
  @Override
  public Row13<String, String, String, String, String, String, Boolean, String, String, OffsetDateTime, OffsetDateTime, String, String> valuesRow() {
    return (Row13) super.valuesRow();
  }

  /**
   * {@inheritDoc}
   */
  @Override
  public Field<String> field1() {
    return FormMetadata.FORM_METADATA.FORM_ID;
  }

  /**
   * {@inheritDoc}
   */
  @Override
  public Field<String> field2() {
    return FormMetadata.FORM_METADATA.FORM_VERSION;
  }

  /**
   * {@inheritDoc}
   */
  @Override
  public Field<String> field3() {
    return FormMetadata.FORM_METADATA.FORM_NAME;
  }

  /**
   * {@inheritDoc}
   */
  @Override
  public Field<String> field4() {
    return FormMetadata.FORM_METADATA.FORM_FILE;
  }

  /**
   * {@inheritDoc}
   */
  @Override
  public Field<String> field5() {
    return FormMetadata.FORM_METADATA.CURSOR_TYPE;
  }

  /**
   * {@inheritDoc}
   */
  @Override
  public Field<String> field6() {
    return FormMetadata.FORM_METADATA.CURSOR_VALUE;
  }

  /**
   * {@inheritDoc}
   */
  @Override
  public Field<Boolean> field7() {
    return FormMetadata.FORM_METADATA.IS_ENCRYPTED;
  }

  /**
   * {@inheritDoc}
   */
  @Override
  public Field<String> field8() {
    return FormMetadata.FORM_METADATA.URL_MANIFEST;
  }

  /**
   * {@inheritDoc}
   */
  @Override
  public Field<String> field9() {
    return FormMetadata.FORM_METADATA.URL_DOWNLOAD;
  }

  /**
   * {@inheritDoc}
   */
  @Override
  public Field<OffsetDateTime> field10() {
    return FormMetadata.FORM_METADATA.LAST_EXPORTED_DATE_TIME;
  }

  /**
   * {@inheritDoc}
   */
  @Override
  public Field<OffsetDateTime> field11() {
    return FormMetadata.FORM_METADATA.LAST_EXPORTED_SUBMISSION_DATE_TIME;
  }

  /**
   * {@inheritDoc}
   */
  @Override
  public Field<String> field12() {
    return FormMetadata.FORM_METADATA.PULL_SOURCE;
  }

  /**
   * {@inheritDoc}
   */
  @Override
  public Field<String> field13() {
    return FormMetadata.FORM_METADATA.EXPORT_CONFIGURATION;
  }

  /**
   * {@inheritDoc}
   */
  @Override
  public String component1() {
    return getFormId();
  }

  /**
   * {@inheritDoc}
   */
  @Override
  public String component2() {
    return getFormVersion();
  }

  /**
   * {@inheritDoc}
   */
  @Override
  public String component3() {
    return getFormName();
  }

  /**
   * {@inheritDoc}
   */
  @Override
  public String component4() {
    return getFormFile();
  }

  /**
   * {@inheritDoc}
   */
  @Override
  public String component5() {
    return getCursorType();
  }

  /**
   * {@inheritDoc}
   */
  @Override
  public String component6() {
    return getCursorValue();
  }

  /**
   * {@inheritDoc}
   */
  @Override
  public Boolean component7() {
    return getIsEncrypted();
  }

  /**
   * {@inheritDoc}
   */
  @Override
  public String component8() {
    return getUrlManifest();
  }

  /**
   * {@inheritDoc}
   */
  @Override
  public String component9() {
    return getUrlDownload();
  }

  /**
   * {@inheritDoc}
   */
  @Override
  public OffsetDateTime component10() {
    return getLastExportedDateTime();
  }

  /**
   * {@inheritDoc}
   */
  @Override
  public OffsetDateTime component11() {
    return getLastExportedSubmissionDateTime();
  }

  /**
   * {@inheritDoc}
   */
  @Override
  public String component12() {
    return getPullSource();
  }

  /**
   * {@inheritDoc}
   */
  @Override
  public String component13() {
    return getExportConfiguration();
  }

  /**
   * {@inheritDoc}
   */
  @Override
  public String value1() {
    return getFormId();
  }

  /**
   * {@inheritDoc}
   */
  @Override
  public String value2() {
    return getFormVersion();
  }

  /**
   * {@inheritDoc}
   */
  @Override
  public String value3() {
    return getFormName();
  }

  /**
   * {@inheritDoc}
   */
  @Override
  public String value4() {
    return getFormFile();
  }

  /**
   * {@inheritDoc}
   */
  @Override
  public String value5() {
    return getCursorType();
  }

  /**
   * {@inheritDoc}
   */
  @Override
  public String value6() {
    return getCursorValue();
  }

  /**
   * {@inheritDoc}
   */
  @Override
  public Boolean value7() {
    return getIsEncrypted();
  }

  /**
   * {@inheritDoc}
   */
  @Override
  public String value8() {
    return getUrlManifest();
  }

  /**
   * {@inheritDoc}
   */
  @Override
  public String value9() {
    return getUrlDownload();
  }

  /**
   * {@inheritDoc}
   */
  @Override
  public OffsetDateTime value10() {
    return getLastExportedDateTime();
  }

  /**
   * {@inheritDoc}
   */
  @Override
  public OffsetDateTime value11() {
    return getLastExportedSubmissionDateTime();
  }

  /**
   * {@inheritDoc}
   */
  @Override
  public String value12() {
    return getPullSource();
  }

  /**
   * {@inheritDoc}
   */
  @Override
  public String value13() {
    return getExportConfiguration();
  }

  /**
   * {@inheritDoc}
   */
  @Override
  public FormMetadataRecord value1(String value) {
    setFormId(value);
    return this;
  }

  /**
   * {@inheritDoc}
   */
  @Override
  public FormMetadataRecord value2(String value) {
    setFormVersion(value);
    return this;
  }

  /**
   * {@inheritDoc}
   */
  @Override
  public FormMetadataRecord value3(String value) {
    setFormName(value);
    return this;
  }

  /**
   * {@inheritDoc}
   */
  @Override
  public FormMetadataRecord value4(String value) {
    setFormFile(value);
    return this;
  }

  /**
   * {@inheritDoc}
   */
  @Override
  public FormMetadataRecord value5(String value) {
    setCursorType(value);
    return this;
  }

  /**
   * {@inheritDoc}
   */
  @Override
  public FormMetadataRecord value6(String value) {
    setCursorValue(value);
    return this;
  }

  /**
   * {@inheritDoc}
   */
  @Override
  public FormMetadataRecord value7(Boolean value) {
    setIsEncrypted(value);
    return this;
  }

  /**
   * {@inheritDoc}
   */
  @Override
  public FormMetadataRecord value8(String value) {
    setUrlManifest(value);
    return this;
  }

  /**
   * {@inheritDoc}
   */
  @Override
  public FormMetadataRecord value9(String value) {
    setUrlDownload(value);
    return this;
  }

  /**
   * {@inheritDoc}
   */
  @Override
  public FormMetadataRecord value10(OffsetDateTime value) {
    setLastExportedDateTime(value);
    return this;
  }

  /**
   * {@inheritDoc}
   */
  @Override
  public FormMetadataRecord value11(OffsetDateTime value) {
    setLastExportedSubmissionDateTime(value);
    return this;
  }

  /**
   * {@inheritDoc}
   */
  @Override
  public FormMetadataRecord value12(String value) {
    setPullSource(value);
    return this;
  }

  /**
   * {@inheritDoc}
   */
  @Override
  public FormMetadataRecord value13(String value) {
    setExportConfiguration(value);
    return this;
  }

  /**
   * {@inheritDoc}
   */
  @Override
  public FormMetadataRecord values(String value1, String value2, String value3, String value4, String value5, String value6, Boolean value7, String value8, String value9, OffsetDateTime value10, OffsetDateTime value11, String value12, String value13) {
    value1(value1);
    value2(value2);
    value3(value3);
    value4(value4);
    value5(value5);
    value6(value6);
    value7(value7);
    value8(value8);
    value9(value9);
    value10(value10);
    value11(value11);
    value12(value12);
    value13(value13);
    return this;
  }

  // -------------------------------------------------------------------------
  // Constructors
  // -------------------------------------------------------------------------

  /**
   * Create a detached FormMetadataRecord
   */
  public FormMetadataRecord() {
    super(FormMetadata.FORM_METADATA);
  }

  /**
   * Create a detached, initialised FormMetadataRecord
   */
  public FormMetadataRecord(String formId, String formVersion, String formName, String formFile, String cursorType, String cursorValue, Boolean isEncrypted, String urlManifest, String urlDownload, OffsetDateTime lastExportedDateTime, OffsetDateTime lastExportedSubmissionDateTime, String pullSource, String exportConfiguration) {
    super(FormMetadata.FORM_METADATA);

    set(0, formId);
    set(1, formVersion);
    set(2, formName);
    set(3, formFile);
    set(4, cursorType);
    set(5, cursorValue);
    set(6, isEncrypted);
    set(7, urlManifest);
    set(8, urlDownload);
    set(9, lastExportedDateTime);
    set(10, lastExportedSubmissionDateTime);
    set(11, pullSource);
    set(12, exportConfiguration);
  }
}
