/*
 * This file is generated by jOOQ.
 */
package org.opendatakit.briefcase.reused.db.jooq.tables.records;


import org.jooq.Field;
import org.jooq.Record3;
import org.jooq.Row3;
import org.jooq.impl.UpdatableRecordImpl;
import org.opendatakit.briefcase.reused.db.jooq.tables.Preference;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({"all", "unchecked", "rawtypes"})
public class PreferenceRecord extends UpdatableRecordImpl<PreferenceRecord> implements Record3<String, String, String> {

  private static final long serialVersionUID = -828041542;

  /**
   * Setter for <code>PUBLIC.PREFERENCE.CATEGORY</code>.
   */
  public void setCategory(String value) {
    set(0, value);
  }

  /**
   * Getter for <code>PUBLIC.PREFERENCE.CATEGORY</code>.
   */
  public String getCategory() {
    return (String) get(0);
  }

  /**
   * Setter for <code>PUBLIC.PREFERENCE.NAME</code>.
   */
  public void setName(String value) {
    set(1, value);
  }

  /**
   * Getter for <code>PUBLIC.PREFERENCE.NAME</code>.
   */
  public String getName() {
    return (String) get(1);
  }

  /**
   * Setter for <code>PUBLIC.PREFERENCE.VALUE</code>.
   */
  public void setValue(String value) {
    set(2, value);
  }

  /**
   * Getter for <code>PUBLIC.PREFERENCE.VALUE</code>.
   */
  public String getValue() {
    return (String) get(2);
  }

  // -------------------------------------------------------------------------
  // Primary key information
  // -------------------------------------------------------------------------

  /**
   * {@inheritDoc}
   */
  @Override
  public Record3<String, String, String> key() {
    return (Record3) super.key();
  }

  // -------------------------------------------------------------------------
  // Record3 type implementation
  // -------------------------------------------------------------------------

  /**
   * {@inheritDoc}
   */
  @Override
  public Row3<String, String, String> fieldsRow() {
    return (Row3) super.fieldsRow();
  }

  /**
   * {@inheritDoc}
   */
  @Override
  public Row3<String, String, String> valuesRow() {
    return (Row3) super.valuesRow();
  }

  /**
   * {@inheritDoc}
   */
  @Override
  public Field<String> field1() {
    return Preference.PREFERENCE.CATEGORY;
  }

  /**
   * {@inheritDoc}
   */
  @Override
  public Field<String> field2() {
    return Preference.PREFERENCE.NAME;
  }

  /**
   * {@inheritDoc}
   */
  @Override
  public Field<String> field3() {
    return Preference.PREFERENCE.VALUE;
  }

  /**
   * {@inheritDoc}
   */
  @Override
  public String component1() {
    return getCategory();
  }

  /**
   * {@inheritDoc}
   */
  @Override
  public String component2() {
    return getName();
  }

  /**
   * {@inheritDoc}
   */
  @Override
  public String component3() {
    return getValue();
  }

  /**
   * {@inheritDoc}
   */
  @Override
  public String value1() {
    return getCategory();
  }

  /**
   * {@inheritDoc}
   */
  @Override
  public String value2() {
    return getName();
  }

  /**
   * {@inheritDoc}
   */
  @Override
  public String value3() {
    return getValue();
  }

  /**
   * {@inheritDoc}
   */
  @Override
  public PreferenceRecord value1(String value) {
    setCategory(value);
    return this;
  }

  /**
   * {@inheritDoc}
   */
  @Override
  public PreferenceRecord value2(String value) {
    setName(value);
    return this;
  }

  /**
   * {@inheritDoc}
   */
  @Override
  public PreferenceRecord value3(String value) {
    setValue(value);
    return this;
  }

  /**
   * {@inheritDoc}
   */
  @Override
  public PreferenceRecord values(String value1, String value2, String value3) {
    value1(value1);
    value2(value2);
    value3(value3);
    return this;
  }

  // -------------------------------------------------------------------------
  // Constructors
  // -------------------------------------------------------------------------

  /**
   * Create a detached PreferenceRecord
   */
  public PreferenceRecord() {
    super(Preference.PREFERENCE);
  }

  /**
   * Create a detached, initialised PreferenceRecord
   */
  public PreferenceRecord(String category, String name, String value) {
    super(Preference.PREFERENCE);

    set(0, category);
    set(1, name);
    set(2, value);
  }
}
