/*
 * This file is generated by jOOQ.
 */
package org.opendatakit.briefcase.reused.db.jooq.tables.records;


import java.time.OffsetDateTime;
import org.jooq.Field;
import org.jooq.Record2;
import org.jooq.Record8;
import org.jooq.Row8;
import org.jooq.impl.UpdatableRecordImpl;
import org.opendatakit.briefcase.reused.db.jooq.tables.SubmissionMetadata;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({"all", "unchecked", "rawtypes"})
public class SubmissionMetadataRecord extends UpdatableRecordImpl<SubmissionMetadataRecord> implements Record8<Integer, String, String, OffsetDateTime, String, String, String, Object> {

  private static final long serialVersionUID = 108113440;

  /**
   * Setter for <code>PUBLIC.SUBMISSION_METADATA.FORM_METADATA_ID</code>.
   */
  public void setFormMetadataId(Integer value) {
    set(0, value);
  }

  /**
   * Getter for <code>PUBLIC.SUBMISSION_METADATA.FORM_METADATA_ID</code>.
   */
  public Integer getFormMetadataId() {
    return (Integer) get(0);
  }

  /**
   * Setter for <code>PUBLIC.SUBMISSION_METADATA.INSTANCE_ID</code>.
   */
  public void setInstanceId(String value) {
    set(1, value);
  }

  /**
   * Getter for <code>PUBLIC.SUBMISSION_METADATA.INSTANCE_ID</code>.
   */
  public String getInstanceId() {
    return (String) get(1);
  }

  /**
   * Setter for <code>PUBLIC.SUBMISSION_METADATA.SUBMISSION_FILE</code>.
   */
  public void setSubmissionFile(String value) {
    set(2, value);
  }

  /**
   * Getter for <code>PUBLIC.SUBMISSION_METADATA.SUBMISSION_FILE</code>.
   */
  public String getSubmissionFile() {
    return (String) get(2);
  }

  /**
   * Setter for <code>PUBLIC.SUBMISSION_METADATA.SUBMISSION_DATE</code>.
   */
  public void setSubmissionDate(OffsetDateTime value) {
    set(3, value);
  }

  /**
   * Getter for <code>PUBLIC.SUBMISSION_METADATA.SUBMISSION_DATE</code>.
   */
  public OffsetDateTime getSubmissionDate() {
    return (OffsetDateTime) get(3);
  }

  /**
   * Setter for <code>PUBLIC.SUBMISSION_METADATA.ENCRYPTED_XML_FILE</code>.
   */
  public void setEncryptedXmlFile(String value) {
    set(4, value);
  }

  /**
   * Getter for <code>PUBLIC.SUBMISSION_METADATA.ENCRYPTED_XML_FILE</code>.
   */
  public String getEncryptedXmlFile() {
    return (String) get(4);
  }

  /**
   * Setter for <code>PUBLIC.SUBMISSION_METADATA.BASE_64_ENCRYPTED_KEY</code>.
   */
  public void setBase_64EncryptedKey(String value) {
    set(5, value);
  }

  /**
   * Getter for <code>PUBLIC.SUBMISSION_METADATA.BASE_64_ENCRYPTED_KEY</code>.
   */
  public String getBase_64EncryptedKey() {
    return (String) get(5);
  }

  /**
   * Setter for <code>PUBLIC.SUBMISSION_METADATA.ENCRYPTED_SIGNATURE</code>.
   */
  public void setEncryptedSignature(String value) {
    set(6, value);
  }

  /**
   * Getter for <code>PUBLIC.SUBMISSION_METADATA.ENCRYPTED_SIGNATURE</code>.
   */
  public String getEncryptedSignature() {
    return (String) get(6);
  }

  /**
   * @deprecated Unknown data type. Please define an explicit {@link org.jooq.Binding} to specify how this type should be handled. Deprecation can be turned off using {@literal <deprecationOnUnknownTypes/>} in your code generator configuration.
   */
  @java.lang.Deprecated
  public void setAttachmentFilenames(Object value) {
    set(7, value);
  }

  /**
   * @deprecated Unknown data type. Please define an explicit {@link org.jooq.Binding} to specify how this type should be handled. Deprecation can be turned off using {@literal <deprecationOnUnknownTypes/>} in your code generator configuration.
   */
  @java.lang.Deprecated
  public Object getAttachmentFilenames() {
    return get(7);
  }

  // -------------------------------------------------------------------------
  // Primary key information
  // -------------------------------------------------------------------------

  /**
   * {@inheritDoc}
   */
  @Override
  public Record2<Integer, String> key() {
    return (Record2) super.key();
  }

  // -------------------------------------------------------------------------
  // Record8 type implementation
  // -------------------------------------------------------------------------

  /**
   * {@inheritDoc}
   */
  @Override
  public Row8<Integer, String, String, OffsetDateTime, String, String, String, Object> fieldsRow() {
    return (Row8) super.fieldsRow();
  }

  /**
   * {@inheritDoc}
   */
  @Override
  public Row8<Integer, String, String, OffsetDateTime, String, String, String, Object> valuesRow() {
    return (Row8) super.valuesRow();
  }

  /**
   * {@inheritDoc}
   */
  @Override
  public Field<Integer> field1() {
    return SubmissionMetadata.SUBMISSION_METADATA.FORM_METADATA_ID;
  }

  /**
   * {@inheritDoc}
   */
  @Override
  public Field<String> field2() {
    return SubmissionMetadata.SUBMISSION_METADATA.INSTANCE_ID;
  }

  /**
   * {@inheritDoc}
   */
  @Override
  public Field<String> field3() {
    return SubmissionMetadata.SUBMISSION_METADATA.SUBMISSION_FILE;
  }

  /**
   * {@inheritDoc}
   */
  @Override
  public Field<OffsetDateTime> field4() {
    return SubmissionMetadata.SUBMISSION_METADATA.SUBMISSION_DATE;
  }

  /**
   * {@inheritDoc}
   */
  @Override
  public Field<String> field5() {
    return SubmissionMetadata.SUBMISSION_METADATA.ENCRYPTED_XML_FILE;
  }

  /**
   * {@inheritDoc}
   */
  @Override
  public Field<String> field6() {
    return SubmissionMetadata.SUBMISSION_METADATA.BASE_64_ENCRYPTED_KEY;
  }

  /**
   * {@inheritDoc}
   */
  @Override
  public Field<String> field7() {
    return SubmissionMetadata.SUBMISSION_METADATA.ENCRYPTED_SIGNATURE;
  }

  /**
   * @deprecated Unknown data type. Please define an explicit {@link org.jooq.Binding} to specify how this type should be handled. Deprecation can be turned off using {@literal <deprecationOnUnknownTypes/>} in your code generator configuration.
   */
  @java.lang.Deprecated
  @Override
  public Field<Object> field8() {
    return SubmissionMetadata.SUBMISSION_METADATA.ATTACHMENT_FILENAMES;
  }

  /**
   * {@inheritDoc}
   */
  @Override
  public Integer component1() {
    return getFormMetadataId();
  }

  /**
   * {@inheritDoc}
   */
  @Override
  public String component2() {
    return getInstanceId();
  }

  /**
   * {@inheritDoc}
   */
  @Override
  public String component3() {
    return getSubmissionFile();
  }

  /**
   * {@inheritDoc}
   */
  @Override
  public OffsetDateTime component4() {
    return getSubmissionDate();
  }

  /**
   * {@inheritDoc}
   */
  @Override
  public String component5() {
    return getEncryptedXmlFile();
  }

  /**
   * {@inheritDoc}
   */
  @Override
  public String component6() {
    return getBase_64EncryptedKey();
  }

  /**
   * {@inheritDoc}
   */
  @Override
  public String component7() {
    return getEncryptedSignature();
  }

  /**
   * @deprecated Unknown data type. Please define an explicit {@link org.jooq.Binding} to specify how this type should be handled. Deprecation can be turned off using {@literal <deprecationOnUnknownTypes/>} in your code generator configuration.
   */
  @java.lang.Deprecated
  @Override
  public Object component8() {
    return getAttachmentFilenames();
  }

  /**
   * {@inheritDoc}
   */
  @Override
  public Integer value1() {
    return getFormMetadataId();
  }

  /**
   * {@inheritDoc}
   */
  @Override
  public String value2() {
    return getInstanceId();
  }

  /**
   * {@inheritDoc}
   */
  @Override
  public String value3() {
    return getSubmissionFile();
  }

  /**
   * {@inheritDoc}
   */
  @Override
  public OffsetDateTime value4() {
    return getSubmissionDate();
  }

  /**
   * {@inheritDoc}
   */
  @Override
  public String value5() {
    return getEncryptedXmlFile();
  }

  /**
   * {@inheritDoc}
   */
  @Override
  public String value6() {
    return getBase_64EncryptedKey();
  }

  /**
   * {@inheritDoc}
   */
  @Override
  public String value7() {
    return getEncryptedSignature();
  }

  /**
   * @deprecated Unknown data type. Please define an explicit {@link org.jooq.Binding} to specify how this type should be handled. Deprecation can be turned off using {@literal <deprecationOnUnknownTypes/>} in your code generator configuration.
   */
  @java.lang.Deprecated
  @Override
  public Object value8() {
    return getAttachmentFilenames();
  }

  /**
   * {@inheritDoc}
   */
  @Override
  public SubmissionMetadataRecord value1(Integer value) {
    setFormMetadataId(value);
    return this;
  }

  /**
   * {@inheritDoc}
   */
  @Override
  public SubmissionMetadataRecord value2(String value) {
    setInstanceId(value);
    return this;
  }

  /**
   * {@inheritDoc}
   */
  @Override
  public SubmissionMetadataRecord value3(String value) {
    setSubmissionFile(value);
    return this;
  }

  /**
   * {@inheritDoc}
   */
  @Override
  public SubmissionMetadataRecord value4(OffsetDateTime value) {
    setSubmissionDate(value);
    return this;
  }

  /**
   * {@inheritDoc}
   */
  @Override
  public SubmissionMetadataRecord value5(String value) {
    setEncryptedXmlFile(value);
    return this;
  }

  /**
   * {@inheritDoc}
   */
  @Override
  public SubmissionMetadataRecord value6(String value) {
    setBase_64EncryptedKey(value);
    return this;
  }

  /**
   * {@inheritDoc}
   */
  @Override
  public SubmissionMetadataRecord value7(String value) {
    setEncryptedSignature(value);
    return this;
  }

  /**
   * @deprecated Unknown data type. Please define an explicit {@link org.jooq.Binding} to specify how this type should be handled. Deprecation can be turned off using {@literal <deprecationOnUnknownTypes/>} in your code generator configuration.
   */
  @java.lang.Deprecated
  @Override
  public SubmissionMetadataRecord value8(Object value) {
    setAttachmentFilenames(value);
    return this;
  }

  /**
   * {@inheritDoc}
   */
  @Override
  public SubmissionMetadataRecord values(Integer value1, String value2, String value3, OffsetDateTime value4, String value5, String value6, String value7, Object value8) {
    value1(value1);
    value2(value2);
    value3(value3);
    value4(value4);
    value5(value5);
    value6(value6);
    value7(value7);
    value8(value8);
    return this;
  }

  // -------------------------------------------------------------------------
  // Constructors
  // -------------------------------------------------------------------------

  /**
   * Create a detached SubmissionMetadataRecord
   */
  public SubmissionMetadataRecord() {
    super(SubmissionMetadata.SUBMISSION_METADATA);
  }

  /**
   * Create a detached, initialised SubmissionMetadataRecord
   */
  public SubmissionMetadataRecord(Integer formMetadataId, String instanceId, String submissionFile, OffsetDateTime submissionDate, String encryptedXmlFile, String base_64EncryptedKey, String encryptedSignature, Object attachmentFilenames) {
    super(SubmissionMetadata.SUBMISSION_METADATA);

    set(0, formMetadataId);
    set(1, instanceId);
    set(2, submissionFile);
    set(3, submissionDate);
    set(4, encryptedXmlFile);
    set(5, base_64EncryptedKey);
    set(6, encryptedSignature);
    set(7, attachmentFilenames);
  }
}
