/*
 * This file is generated by jOOQ.
 */
package org.opendatakit.briefcase.jooq.tables.records;


import java.time.OffsetDateTime;
import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record9;
import org.jooq.Row9;
import org.jooq.impl.UpdatableRecordImpl;
import org.opendatakit.briefcase.jooq.tables.FormMetadata;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({"all", "unchecked", "rawtypes"})
public class FormMetadataRecord extends UpdatableRecordImpl<FormMetadataRecord> implements Record9<Integer, String, String, String, String, String, String, String, OffsetDateTime> {

  private static final long serialVersionUID = 1758337666;

  /**
   * Setter for <code>PUBLIC.FORM_METADATA.ID</code>.
   */
  public void setId(Integer value) {
    set(0, value);
  }

  /**
   * Getter for <code>PUBLIC.FORM_METADATA.ID</code>.
   */
  public Integer getId() {
    return (Integer) get(0);
  }

  /**
   * Setter for <code>PUBLIC.FORM_METADATA.FORM_NAME</code>.
   */
  public void setFormName(String value) {
    set(1, value);
  }

  /**
   * Getter for <code>PUBLIC.FORM_METADATA.FORM_NAME</code>.
   */
  public String getFormName() {
    return (String) get(1);
  }

  /**
   * Setter for <code>PUBLIC.FORM_METADATA.FORM_ID</code>.
   */
  public void setFormId(String value) {
    set(2, value);
  }

  /**
   * Getter for <code>PUBLIC.FORM_METADATA.FORM_ID</code>.
   */
  public String getFormId() {
    return (String) get(2);
  }

  /**
   * Setter for <code>PUBLIC.FORM_METADATA.FORM_VERSION</code>.
   */
  public void setFormVersion(String value) {
    set(3, value);
  }

  /**
   * Getter for <code>PUBLIC.FORM_METADATA.FORM_VERSION</code>.
   */
  public String getFormVersion() {
    return (String) get(3);
  }

  /**
   * Setter for <code>PUBLIC.FORM_METADATA.FORM_DIR</code>.
   */
  public void setFormDir(String value) {
    set(4, value);
  }

  /**
   * Getter for <code>PUBLIC.FORM_METADATA.FORM_DIR</code>.
   */
  public String getFormDir() {
    return (String) get(4);
  }

  /**
   * Setter for <code>PUBLIC.FORM_METADATA.FORM_FILENAME</code>.
   */
  public void setFormFilename(String value) {
    set(5, value);
  }

  /**
   * Getter for <code>PUBLIC.FORM_METADATA.FORM_FILENAME</code>.
   */
  public String getFormFilename() {
    return (String) get(5);
  }

  /**
   * Setter for <code>PUBLIC.FORM_METADATA.CURSOR_TYPE</code>.
   */
  public void setCursorType(String value) {
    set(6, value);
  }

  /**
   * Getter for <code>PUBLIC.FORM_METADATA.CURSOR_TYPE</code>.
   */
  public String getCursorType() {
    return (String) get(6);
  }

  /**
   * Setter for <code>PUBLIC.FORM_METADATA.CURSOR_VALUE</code>.
   */
  public void setCursorValue(String value) {
    set(7, value);
  }

  /**
   * Getter for <code>PUBLIC.FORM_METADATA.CURSOR_VALUE</code>.
   */
  public String getCursorValue() {
    return (String) get(7);
  }

  /**
   * Setter for <code>PUBLIC.FORM_METADATA.LAST_EXPORTED_SUBMISSION_DATE</code>.
   */
  public void setLastExportedSubmissionDate(OffsetDateTime value) {
    set(8, value);
  }

  /**
   * Getter for <code>PUBLIC.FORM_METADATA.LAST_EXPORTED_SUBMISSION_DATE</code>.
   */
  public OffsetDateTime getLastExportedSubmissionDate() {
    return (OffsetDateTime) get(8);
  }

  // -------------------------------------------------------------------------
  // Primary key information
  // -------------------------------------------------------------------------

  /**
   * {@inheritDoc}
   */
  @Override
  public Record1<Integer> key() {
    return (Record1) super.key();
  }

  // -------------------------------------------------------------------------
  // Record9 type implementation
  // -------------------------------------------------------------------------

  /**
   * {@inheritDoc}
   */
  @Override
  public Row9<Integer, String, String, String, String, String, String, String, OffsetDateTime> fieldsRow() {
    return (Row9) super.fieldsRow();
  }

  /**
   * {@inheritDoc}
   */
  @Override
  public Row9<Integer, String, String, String, String, String, String, String, OffsetDateTime> valuesRow() {
    return (Row9) super.valuesRow();
  }

  /**
   * {@inheritDoc}
   */
  @Override
  public Field<Integer> field1() {
    return FormMetadata.FORM_METADATA.ID;
  }

  /**
   * {@inheritDoc}
   */
  @Override
  public Field<String> field2() {
    return FormMetadata.FORM_METADATA.FORM_NAME;
  }

  /**
   * {@inheritDoc}
   */
  @Override
  public Field<String> field3() {
    return FormMetadata.FORM_METADATA.FORM_ID;
  }

  /**
   * {@inheritDoc}
   */
  @Override
  public Field<String> field4() {
    return FormMetadata.FORM_METADATA.FORM_VERSION;
  }

  /**
   * {@inheritDoc}
   */
  @Override
  public Field<String> field5() {
    return FormMetadata.FORM_METADATA.FORM_DIR;
  }

  /**
   * {@inheritDoc}
   */
  @Override
  public Field<String> field6() {
    return FormMetadata.FORM_METADATA.FORM_FILENAME;
  }

  /**
   * {@inheritDoc}
   */
  @Override
  public Field<String> field7() {
    return FormMetadata.FORM_METADATA.CURSOR_TYPE;
  }

  /**
   * {@inheritDoc}
   */
  @Override
  public Field<String> field8() {
    return FormMetadata.FORM_METADATA.CURSOR_VALUE;
  }

  /**
   * {@inheritDoc}
   */
  @Override
  public Field<OffsetDateTime> field9() {
    return FormMetadata.FORM_METADATA.LAST_EXPORTED_SUBMISSION_DATE;
  }

  /**
   * {@inheritDoc}
   */
  @Override
  public Integer component1() {
    return getId();
  }

  /**
   * {@inheritDoc}
   */
  @Override
  public String component2() {
    return getFormName();
  }

  /**
   * {@inheritDoc}
   */
  @Override
  public String component3() {
    return getFormId();
  }

  /**
   * {@inheritDoc}
   */
  @Override
  public String component4() {
    return getFormVersion();
  }

  /**
   * {@inheritDoc}
   */
  @Override
  public String component5() {
    return getFormDir();
  }

  /**
   * {@inheritDoc}
   */
  @Override
  public String component6() {
    return getFormFilename();
  }

  /**
   * {@inheritDoc}
   */
  @Override
  public String component7() {
    return getCursorType();
  }

  /**
   * {@inheritDoc}
   */
  @Override
  public String component8() {
    return getCursorValue();
  }

  /**
   * {@inheritDoc}
   */
  @Override
  public OffsetDateTime component9() {
    return getLastExportedSubmissionDate();
  }

  /**
   * {@inheritDoc}
   */
  @Override
  public Integer value1() {
    return getId();
  }

  /**
   * {@inheritDoc}
   */
  @Override
  public String value2() {
    return getFormName();
  }

  /**
   * {@inheritDoc}
   */
  @Override
  public String value3() {
    return getFormId();
  }

  /**
   * {@inheritDoc}
   */
  @Override
  public String value4() {
    return getFormVersion();
  }

  /**
   * {@inheritDoc}
   */
  @Override
  public String value5() {
    return getFormDir();
  }

  /**
   * {@inheritDoc}
   */
  @Override
  public String value6() {
    return getFormFilename();
  }

  /**
   * {@inheritDoc}
   */
  @Override
  public String value7() {
    return getCursorType();
  }

  /**
   * {@inheritDoc}
   */
  @Override
  public String value8() {
    return getCursorValue();
  }

  /**
   * {@inheritDoc}
   */
  @Override
  public OffsetDateTime value9() {
    return getLastExportedSubmissionDate();
  }

  /**
   * {@inheritDoc}
   */
  @Override
  public FormMetadataRecord value1(Integer value) {
    setId(value);
    return this;
  }

  /**
   * {@inheritDoc}
   */
  @Override
  public FormMetadataRecord value2(String value) {
    setFormName(value);
    return this;
  }

  /**
   * {@inheritDoc}
   */
  @Override
  public FormMetadataRecord value3(String value) {
    setFormId(value);
    return this;
  }

  /**
   * {@inheritDoc}
   */
  @Override
  public FormMetadataRecord value4(String value) {
    setFormVersion(value);
    return this;
  }

  /**
   * {@inheritDoc}
   */
  @Override
  public FormMetadataRecord value5(String value) {
    setFormDir(value);
    return this;
  }

  /**
   * {@inheritDoc}
   */
  @Override
  public FormMetadataRecord value6(String value) {
    setFormFilename(value);
    return this;
  }

  /**
   * {@inheritDoc}
   */
  @Override
  public FormMetadataRecord value7(String value) {
    setCursorType(value);
    return this;
  }

  /**
   * {@inheritDoc}
   */
  @Override
  public FormMetadataRecord value8(String value) {
    setCursorValue(value);
    return this;
  }

  /**
   * {@inheritDoc}
   */
  @Override
  public FormMetadataRecord value9(OffsetDateTime value) {
    setLastExportedSubmissionDate(value);
    return this;
  }

  /**
   * {@inheritDoc}
   */
  @Override
  public FormMetadataRecord values(Integer value1, String value2, String value3, String value4, String value5, String value6, String value7, String value8, OffsetDateTime value9) {
    value1(value1);
    value2(value2);
    value3(value3);
    value4(value4);
    value5(value5);
    value6(value6);
    value7(value7);
    value8(value8);
    value9(value9);
    return this;
  }

  // -------------------------------------------------------------------------
  // Constructors
  // -------------------------------------------------------------------------

  /**
   * Create a detached FormMetadataRecord
   */
  public FormMetadataRecord() {
    super(FormMetadata.FORM_METADATA);
  }

  /**
   * Create a detached, initialised FormMetadataRecord
   */
  public FormMetadataRecord(Integer id, String formName, String formId, String formVersion, String formDir, String formFilename, String cursorType, String cursorValue, OffsetDateTime lastExportedSubmissionDate) {
    super(FormMetadata.FORM_METADATA);

    set(0, id);
    set(1, formName);
    set(2, formId);
    set(3, formVersion);
    set(4, formDir);
    set(5, formFilename);
    set(6, cursorType);
    set(7, cursorValue);
    set(8, lastExportedSubmissionDate);
  }
}
