/*
 * Copyright (C) 2018 Nafundi
 *
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not
 * use this file except in compliance with the License. You may obtain a copy of
 * the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
 * WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
 * License for the specific language governing permissions and limitations under
 * the License.
 */

package org.opendatakit.briefcase.ui.reused.transfer.sourcetarget;

import java.awt.CardLayout;
import java.util.HashMap;
import java.util.Map;
import javax.swing.JComponent;
import javax.swing.JPanel;

@SuppressWarnings("checkstyle:MethodName")
public class SourceOrTargetPanelForm extends JComponent {
  public JPanel container;
  private Map<Object, JPanel> forms = new HashMap<>();

  SourceOrTargetPanelForm() {
    $$$setupUI$$$();
  }

  void addForm(Object key, JPanel form) {
    forms.put(key, form);
    container.add(form);
  }

  void navigateTo(Object key) {
    if (!forms.containsKey(key))
      throw new IllegalArgumentException("Navigation error : key " + key + " not found");

    forms.forEach((s, jpanel) -> jpanel.setVisible(false));
    forms.get(key).setVisible(true);
  }

  /**
   * Method generated by IntelliJ IDEA GUI Designer
   * >>> IMPORTANT!! <<<
   * DO NOT edit this method OR call it in your code!
   *
   * @noinspection ALL
   */
  private void $$$setupUI$$$() {
    container = new JPanel();
    container.setLayout(new CardLayout(0, 0));
  }

  /**
   * @noinspection ALL
   */
  public JComponent $$$getRootComponent$$$() {
    return container;
  }
}
