/*
 * Copyright (C) 2018 Nafundi
 *
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not
 * use this file except in compliance with the License. You may obtain a copy of
 * the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
 * WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
 * License for the specific language governing permissions and limitations under
 * the License.
 */

package org.opendatakit.briefcase.ui.push;

import java.awt.CardLayout;
import java.awt.FlowLayout;
import java.awt.GridBagConstraints;
import java.awt.GridBagLayout;
import java.util.ArrayList;
import java.util.List;
import java.util.Optional;
import java.util.function.Consumer;
import javax.swing.JButton;
import javax.swing.JComponent;
import javax.swing.JPanel;
import javax.swing.JProgressBar;
import javax.swing.JScrollPane;
import org.opendatakit.briefcase.reused.RemoteServer;
import org.opendatakit.briefcase.ui.push.components.PushFormsTable;
import org.opendatakit.briefcase.ui.push.components.PushFormsTableView;
import org.opendatakit.briefcase.ui.reused.source.Source;
import org.opendatakit.briefcase.ui.reused.source.SourcePanel;
import org.opendatakit.briefcase.ui.reused.source.SourcePanelForm;

@SuppressWarnings("checkstyle:MethodName")
public class PushPanelForm {
  public JPanel container;
  private SourcePanel sourcePanel;
  private SourcePanelForm sourcePanelForm;
  private JPanel top;
  private JPanel actions;
  private final PushFormsTable pushFormsTable;
  private final PushFormsTableView pushFormsTableView;
  private JScrollPane scrollPane;
  private JButton selectAllButton;
  private JButton clearAllButton;
  private JButton pushButton;
  private JButton cancelButton;
  private JPanel leftActions;
  private JPanel rightActions;
  private JProgressBar pushProgressBar;
  private boolean pushing = false;
  private final List<Runnable> onChangeCallbacks = new ArrayList<>();

  public PushPanelForm(SourcePanel sourcePanel, PushFormsTable pushFormsTable) {
    this.sourcePanel = sourcePanel;
    this.sourcePanelForm = sourcePanel.getContainer();
    this.pushFormsTable = pushFormsTable;
    this.pushFormsTableView = pushFormsTable.getView();
    $$$setupUI$$$();

    pushFormsTable.onChange(this::triggerOnChange);
    selectAllButton.addActionListener(__ -> pushFormsTable.selectAll());
    clearAllButton.addActionListener(__ -> pushFormsTable.clearAll());
  }

  public void onSource(Consumer<Source<?>> callback) {
    sourcePanel.onSource(callback);
  }

  public void onReset(Runnable callback) {
    sourcePanel.onReset(callback);
  }

  private void triggerOnChange() {
    onChangeCallbacks.forEach(Runnable::run);
  }

  public void onChange(Runnable runnable) {
    onChangeCallbacks.add(runnable);
  }

  public void onPush(Runnable callback) {
    pushButton.addActionListener(__ -> callback.run());
  }

  public void onCancel(Runnable callback) {
    cancelButton.addActionListener(__ -> callback.run());
  }

  public void refresh() {
    pushFormsTable.refresh();
  }

  public void showClearAll() {
    selectAllButton.setVisible(false);
    clearAllButton.setVisible(true);
  }

  public void showSelectAll() {
    selectAllButton.setVisible(true);
    clearAllButton.setVisible(false);
  }

  public void enableSelectAll() {
    selectAllButton.setEnabled(!pushing);
  }

  public void disableSelectAll() {
    selectAllButton.setEnabled(false);
  }

  public void enablePush() {
    pushButton.setEnabled(!pushing);
  }

  public void disablePush() {
    pushButton.setEnabled(false);
  }

  public void setPushing() {
    pushing = true;
    pushProgressBar.setVisible(true);
    sourcePanel.disableInteraction();
    pushFormsTable.disableInteraction();
    selectAllButton.setEnabled(false);
    clearAllButton.setEnabled(false);
    cancelButton.setVisible(true);
    cancelButton.setEnabled(true);
    pushButton.setVisible(false);
  }

  public void unsetPushing() {
    pushing = false;
    pushProgressBar.setVisible(false);
    sourcePanel.enableInteraction();
    pushFormsTable.enableInteraction();
    selectAllButton.setEnabled(true);
    clearAllButton.setEnabled(true);
    cancelButton.setVisible(false);
    cancelButton.setEnabled(false);
    pushButton.setVisible(true);
  }

  public Optional<Source<?>> preloadSource(RemoteServer server) {
    return sourcePanel.preload(server);
  }

  private void createUIComponents() {

  }

  /**
   * Method generated by IntelliJ IDEA GUI Designer
   * >>> IMPORTANT!! <<<
   * DO NOT edit this method OR call it in your code!
   *
   * @noinspection ALL
   */
  private void $$$setupUI$$$() {
    createUIComponents();
    container = new JPanel();
    container.setLayout(new GridBagLayout());
    top = new JPanel();
    top.setLayout(new CardLayout(0, 0));
    GridBagConstraints gbc;
    gbc = new GridBagConstraints();
    gbc.gridx = 1;
    gbc.gridy = 1;
    gbc.weightx = 1.0;
    gbc.fill = GridBagConstraints.BOTH;
    container.add(top, gbc);
    top.add(sourcePanelForm.$$$getRootComponent$$$(), "Card1");
    final JPanel spacer1 = new JPanel();
    gbc = new GridBagConstraints();
    gbc.gridx = 1;
    gbc.gridy = 0;
    gbc.fill = GridBagConstraints.VERTICAL;
    container.add(spacer1, gbc);
    final JPanel spacer2 = new JPanel();
    gbc = new GridBagConstraints();
    gbc.gridx = 1;
    gbc.gridy = 4;
    gbc.fill = GridBagConstraints.VERTICAL;
    container.add(spacer2, gbc);
    final JPanel spacer3 = new JPanel();
    gbc = new GridBagConstraints();
    gbc.gridx = 1;
    gbc.gridy = 2;
    gbc.fill = GridBagConstraints.VERTICAL;
    container.add(spacer3, gbc);
    final JPanel spacer4 = new JPanel();
    gbc = new GridBagConstraints();
    gbc.gridx = 1;
    gbc.gridy = 6;
    gbc.fill = GridBagConstraints.VERTICAL;
    container.add(spacer4, gbc);
    scrollPane = new JScrollPane();
    gbc = new GridBagConstraints();
    gbc.gridx = 1;
    gbc.gridy = 3;
    gbc.weightx = 1.0;
    gbc.weighty = 1.0;
    gbc.fill = GridBagConstraints.BOTH;
    container.add(scrollPane, gbc);
    scrollPane.setViewportView(pushFormsTableView);
    actions = new JPanel();
    actions.setLayout(new GridBagLayout());
    gbc = new GridBagConstraints();
    gbc.gridx = 1;
    gbc.gridy = 5;
    gbc.fill = GridBagConstraints.BOTH;
    container.add(actions, gbc);
    leftActions = new JPanel();
    leftActions.setLayout(new FlowLayout(FlowLayout.CENTER, 5, 5));
    gbc = new GridBagConstraints();
    gbc.gridx = 0;
    gbc.gridy = 0;
    gbc.fill = GridBagConstraints.BOTH;
    actions.add(leftActions, gbc);
    selectAllButton = new JButton();
    selectAllButton.setEnabled(false);
    selectAllButton.setText("Select All");
    leftActions.add(selectAllButton);
    clearAllButton = new JButton();
    clearAllButton.setText("Clear All");
    clearAllButton.setVisible(false);
    leftActions.add(clearAllButton);
    final JPanel spacer5 = new JPanel();
    gbc = new GridBagConstraints();
    gbc.gridx = 1;
    gbc.gridy = 0;
    gbc.weightx = 1.0;
    gbc.fill = GridBagConstraints.HORIZONTAL;
    actions.add(spacer5, gbc);
    rightActions = new JPanel();
    rightActions.setLayout(new FlowLayout(FlowLayout.CENTER, 5, 5));
    gbc = new GridBagConstraints();
    gbc.gridx = 2;
    gbc.gridy = 0;
    gbc.fill = GridBagConstraints.BOTH;
    actions.add(rightActions, gbc);
    pushProgressBar = new JProgressBar();
    pushProgressBar.setIndeterminate(true);
    pushProgressBar.setVisible(false);
    rightActions.add(pushProgressBar);
    pushButton = new JButton();
    pushButton.setEnabled(false);
    pushButton.setText("Push");
    rightActions.add(pushButton);
    cancelButton = new JButton();
    cancelButton.setText("Cancel");
    cancelButton.setVisible(false);
    rightActions.add(cancelButton);
    final JPanel spacer6 = new JPanel();
    gbc = new GridBagConstraints();
    gbc.gridx = 2;
    gbc.gridy = 0;
    gbc.gridheight = 7;
    gbc.fill = GridBagConstraints.HORIZONTAL;
    container.add(spacer6, gbc);
    final JPanel spacer7 = new JPanel();
    gbc = new GridBagConstraints();
    gbc.gridx = 0;
    gbc.gridy = 0;
    gbc.gridheight = 7;
    gbc.fill = GridBagConstraints.HORIZONTAL;
    container.add(spacer7, gbc);
  }

  /**
   * @noinspection ALL
   */
  public JComponent $$$getRootComponent$$$() {
    return container;
  }
}
