/*
 * Copyright (C) 2018 Nafundi
 *
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not
 * use this file except in compliance with the License. You may obtain a copy of
 * the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
 * WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
 * License for the specific language governing permissions and limitations under
 * the License.
 */

package org.opendatakit.briefcase.ui.pull;

import java.awt.CardLayout;
import java.awt.FlowLayout;
import java.awt.GridBagConstraints;
import java.awt.GridBagLayout;
import java.util.ArrayList;
import java.util.List;
import java.util.function.Consumer;
import javax.swing.JButton;
import javax.swing.JComponent;
import javax.swing.JPanel;
import javax.swing.JProgressBar;
import javax.swing.JScrollPane;
import org.opendatakit.briefcase.reused.RemoteServer;
import org.opendatakit.briefcase.ui.pull.components.PullFormsTable;
import org.opendatakit.briefcase.ui.pull.components.PullFormsTableView;
import org.opendatakit.briefcase.ui.reused.source.Source;
import org.opendatakit.briefcase.ui.reused.source.SourcePanel;

@SuppressWarnings("checkstyle:MethodName")
public class PullPanelForm {
  public JPanel container;
  private SourcePanel sourcePanel;
  private JPanel top;
  private JPanel actions;
  private final PullFormsTable pullFormsTable;
  private final PullFormsTableView pullFormsTableView;
  private JScrollPane scrollPane;
  private JButton selectAllButton;
  private JButton clearAllButton;
  private JButton pullButton;
  private JButton cancelButton;
  private JPanel leftActions;
  private JPanel rightActions;
  private JProgressBar pullProgressBar;
  private boolean pulling = false;
  private final List<Runnable> onChangeCallbacks = new ArrayList<>();

  public PullPanelForm(SourcePanel sourcePanel, PullFormsTable pullFormsTable) {
    this.sourcePanel = sourcePanel;
    this.pullFormsTable = pullFormsTable;
    this.pullFormsTableView = pullFormsTable.getView();
    $$$setupUI$$$();

    pullFormsTable.onChange(this::triggerOnChange);
    selectAllButton.addActionListener(__ -> pullFormsTable.selectAll());
    clearAllButton.addActionListener(__ -> pullFormsTable.clearAll());
  }

  public void onSource(Consumer<Source<?>> callback) {
    sourcePanel.onSource(callback);
  }

  public void onReset(Runnable callback) {
    sourcePanel.onReset(callback);
  }

  private void triggerOnChange() {
    onChangeCallbacks.forEach(Runnable::run);
  }

  public void onChange(Runnable runnable) {
    onChangeCallbacks.add(runnable);
  }

  public void onPull(Runnable callback) {
    pullButton.addActionListener(__ -> callback.run());
  }

  public void onCancel(Runnable callback) {
    cancelButton.addActionListener(__ -> callback.run());
  }

  public void refresh() {
    pullFormsTable.refresh();
  }

  public void showClearAll() {
    selectAllButton.setVisible(false);
    clearAllButton.setVisible(true);
  }

  public void showSelectAll() {
    selectAllButton.setVisible(true);
    clearAllButton.setVisible(false);
  }

  public void enableSelectAll() {
    selectAllButton.setEnabled(!pulling);
  }

  public void disableSelectAll() {
    selectAllButton.setEnabled(false);
  }

  public void enablePull() {
    pullButton.setEnabled(!pulling);
  }

  public void disablePull() {
    pullButton.setEnabled(false);
  }

  public void setPulling() {
    pulling = true;
    pullProgressBar.setVisible(true);
    sourcePanel.disableInteraction();
    pullFormsTable.disableInteraction();
    selectAllButton.setEnabled(false);
    clearAllButton.setEnabled(false);
    cancelButton.setVisible(true);
    cancelButton.setEnabled(true);
    pullButton.setVisible(false);
  }

  public void unsetPulling() {
    pulling = false;
    pullProgressBar.setVisible(false);
    sourcePanel.enableInteraction();
    pullFormsTable.enableInteraction();
    selectAllButton.setEnabled(true);
    clearAllButton.setEnabled(true);
    cancelButton.setVisible(false);
    pullButton.setVisible(true);
  }

  public void preloadSource(RemoteServer server) {
    sourcePanel.preload(server);
  }

  private void createUIComponents() {

  }

  /**
   * Method generated by IntelliJ IDEA GUI Designer
   * >>> IMPORTANT!! <<<
   * DO NOT edit this method OR call it in your code!
   *
   * @noinspection ALL
   */
  private void $$$setupUI$$$() {
    createUIComponents();
    container = new JPanel();
    container.setLayout(new GridBagLayout());
    top = new JPanel();
    top.setLayout(new CardLayout(0, 0));
    GridBagConstraints gbc;
    gbc = new GridBagConstraints();
    gbc.gridx = 1;
    gbc.gridy = 1;
    gbc.weightx = 1.0;
    gbc.fill = GridBagConstraints.BOTH;
    container.add(top, gbc);
    top.add(sourcePanel.$$$getRootComponent$$$(), "Card1");
    final JPanel spacer1 = new JPanel();
    gbc = new GridBagConstraints();
    gbc.gridx = 1;
    gbc.gridy = 0;
    gbc.fill = GridBagConstraints.VERTICAL;
    container.add(spacer1, gbc);
    final JPanel spacer2 = new JPanel();
    gbc = new GridBagConstraints();
    gbc.gridx = 1;
    gbc.gridy = 4;
    gbc.fill = GridBagConstraints.VERTICAL;
    container.add(spacer2, gbc);
    final JPanel spacer3 = new JPanel();
    gbc = new GridBagConstraints();
    gbc.gridx = 1;
    gbc.gridy = 2;
    gbc.fill = GridBagConstraints.VERTICAL;
    container.add(spacer3, gbc);
    final JPanel spacer4 = new JPanel();
    gbc = new GridBagConstraints();
    gbc.gridx = 1;
    gbc.gridy = 6;
    gbc.fill = GridBagConstraints.VERTICAL;
    container.add(spacer4, gbc);
    scrollPane = new JScrollPane();
    gbc = new GridBagConstraints();
    gbc.gridx = 1;
    gbc.gridy = 3;
    gbc.weightx = 1.0;
    gbc.weighty = 1.0;
    gbc.fill = GridBagConstraints.BOTH;
    container.add(scrollPane, gbc);
    scrollPane.setViewportView(pullFormsTableView);
    actions = new JPanel();
    actions.setLayout(new GridBagLayout());
    gbc = new GridBagConstraints();
    gbc.gridx = 1;
    gbc.gridy = 5;
    gbc.fill = GridBagConstraints.BOTH;
    container.add(actions, gbc);
    leftActions = new JPanel();
    leftActions.setLayout(new FlowLayout(FlowLayout.CENTER, 5, 5));
    gbc = new GridBagConstraints();
    gbc.gridx = 0;
    gbc.gridy = 0;
    gbc.fill = GridBagConstraints.BOTH;
    actions.add(leftActions, gbc);
    selectAllButton = new JButton();
    selectAllButton.setEnabled(false);
    selectAllButton.setText("Select All");
    leftActions.add(selectAllButton);
    clearAllButton = new JButton();
    clearAllButton.setText("Clear All");
    clearAllButton.setVisible(false);
    leftActions.add(clearAllButton);
    final JPanel spacer5 = new JPanel();
    gbc = new GridBagConstraints();
    gbc.gridx = 1;
    gbc.gridy = 0;
    gbc.weightx = 1.0;
    gbc.fill = GridBagConstraints.HORIZONTAL;
    actions.add(spacer5, gbc);
    rightActions = new JPanel();
    rightActions.setLayout(new FlowLayout(FlowLayout.CENTER, 5, 5));
    gbc = new GridBagConstraints();
    gbc.gridx = 2;
    gbc.gridy = 0;
    gbc.fill = GridBagConstraints.BOTH;
    actions.add(rightActions, gbc);
    pullProgressBar = new JProgressBar();
    pullProgressBar.setIndeterminate(true);
    pullProgressBar.setVisible(false);
    rightActions.add(pullProgressBar);
    pullButton = new JButton();
    pullButton.setEnabled(false);
    pullButton.setText("Pull");
    rightActions.add(pullButton);
    cancelButton = new JButton();
    cancelButton.setText("Cancel");
    cancelButton.setVisible(false);
    rightActions.add(cancelButton);
    final JPanel spacer6 = new JPanel();
    gbc = new GridBagConstraints();
    gbc.gridx = 2;
    gbc.gridy = 0;
    gbc.gridheight = 7;
    gbc.fill = GridBagConstraints.HORIZONTAL;
    container.add(spacer6, gbc);
    final JPanel spacer7 = new JPanel();
    gbc = new GridBagConstraints();
    gbc.gridx = 0;
    gbc.gridy = 0;
    gbc.gridheight = 7;
    gbc.fill = GridBagConstraints.HORIZONTAL;
    container.add(spacer7, gbc);
  }

  /**
   * @noinspection ALL
   */
  public JComponent $$$getRootComponent$$$() {
    return container;
  }
}
