/*
 * This file is generated by jOOQ.
 */
package org.opendatakit.briefcase.reused.db.jooq;


import org.jooq.UniqueKey;
import org.jooq.impl.Internal;
import org.opendatakit.briefcase.reused.db.jooq.tables.FormMetadata;
import org.opendatakit.briefcase.reused.db.jooq.tables.SubmissionMetadata;
import org.opendatakit.briefcase.reused.db.jooq.tables.records.FormMetadataRecord;
import org.opendatakit.briefcase.reused.db.jooq.tables.records.SubmissionMetadataRecord;


/**
 * A class modelling foreign key relationships and constraints of tables of
 * the <code>PUBLIC</code> schema.
 */
@SuppressWarnings({"all", "unchecked", "rawtypes"})
public class Keys {

  // -------------------------------------------------------------------------
  // IDENTITY definitions
  // -------------------------------------------------------------------------


  // -------------------------------------------------------------------------
  // UNIQUE and PRIMARY KEY definitions
  // -------------------------------------------------------------------------

  public static final UniqueKey<FormMetadataRecord> SYS_PK_10132 = UniqueKeys0.SYS_PK_10132;
  public static final UniqueKey<SubmissionMetadataRecord> SYS_PK_10146 = UniqueKeys0.SYS_PK_10146;

  // -------------------------------------------------------------------------
  // FOREIGN KEY definitions
  // -------------------------------------------------------------------------


  // -------------------------------------------------------------------------
  // [#1459] distribute members to avoid static initialisers > 64kb
  // -------------------------------------------------------------------------

  private static class UniqueKeys0 {
    public static final UniqueKey<FormMetadataRecord> SYS_PK_10132 = Internal.createUniqueKey(FormMetadata.FORM_METADATA, "SYS_PK_10132", FormMetadata.FORM_METADATA.FORM_ID, FormMetadata.FORM_METADATA.FORM_VERSION);
    public static final UniqueKey<SubmissionMetadataRecord> SYS_PK_10146 = Internal.createUniqueKey(SubmissionMetadata.SUBMISSION_METADATA, "SYS_PK_10146", SubmissionMetadata.SUBMISSION_METADATA.FORM_ID, SubmissionMetadata.SUBMISSION_METADATA.FORM_VERSION, SubmissionMetadata.SUBMISSION_METADATA.INSTANCE_ID);
  }
}
