/*
 * This file is generated by jOOQ.
 */
package org.opendatakit.briefcase.reused.db.jooq;


import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import org.jooq.Catalog;
import org.jooq.Sequence;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;
import org.opendatakit.briefcase.reused.db.jooq.tables.FormMetadata;
import org.opendatakit.briefcase.reused.db.jooq.tables.SubmissionMetadata;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({"all", "unchecked", "rawtypes"})
public class Public extends SchemaImpl {

  private static final long serialVersionUID = 1008287077;

  /**
   * The reference instance of <code>PUBLIC</code>
   */
  public static final Public PUBLIC = new Public();

  /**
   * The table <code>PUBLIC.FORM_METADATA</code>.
   */
  public final FormMetadata FORM_METADATA = org.opendatakit.briefcase.reused.db.jooq.tables.FormMetadata.FORM_METADATA;

  /**
   * The table <code>PUBLIC.SUBMISSION_METADATA</code>.
   */
  public final SubmissionMetadata SUBMISSION_METADATA = org.opendatakit.briefcase.reused.db.jooq.tables.SubmissionMetadata.SUBMISSION_METADATA;

  /**
   * No further instances allowed
   */
  private Public() {
    super("PUBLIC", null);
  }


  /**
   * {@inheritDoc}
   */
  @Override
  public Catalog getCatalog() {
    return DefaultCatalog.DEFAULT_CATALOG;
  }

  @Override
  public final List<Sequence<?>> getSequences() {
    List result = new ArrayList();
    result.addAll(getSequences0());
    return result;
  }

  private final List<Sequence<?>> getSequences0() {
    return Arrays.<Sequence<?>>asList(
        Sequences.FORM_METADATA_ID_SEQ);
  }

  @Override
  public final List<Table<?>> getTables() {
    List result = new ArrayList();
    result.addAll(getTables0());
    return result;
  }

  private final List<Table<?>> getTables0() {
    return Arrays.<Table<?>>asList(
        FormMetadata.FORM_METADATA,
        SubmissionMetadata.SUBMISSION_METADATA);
  }
}
