package org.opendatakit.briefcase.ui.reused;

import java.awt.GridBagConstraints;
import java.awt.GridBagLayout;
import java.nio.file.Path;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JButton;
import javax.swing.JComponent;
import javax.swing.JLabel;
import javax.swing.JPanel;

@SuppressWarnings("checkstyle:MethodName")
public class SourceDisplayPanelForm extends JComponent {
  public JPanel container;
  private JLabel sourceLabel;
  private JLabel sourceAddressLabel;
  private JButton resetButton;
  private JLabel actionLabel;
  private List<Runnable> onResetCallbacks = new ArrayList<>();

  public SourceDisplayPanelForm(String action, String source, String sourceAddress) {
    $$$setupUI$$$();
    sourceLabel.setText(source);
    sourceAddressLabel.setText(sourceAddress);
    actionLabel.setText(action);

    resetButton.addActionListener(__ -> onResetCallbacks.forEach(Runnable::run));
  }

  static SourceDisplayPanelForm empty(String action) {
    return new SourceDisplayPanelForm(action, "", "");
  }

  public void onReset(Runnable callback) {
    onResetCallbacks.add(callback);
  }

  public void readConfiguration(AggregateServerConnectionConfiguration conf) {
    sourceLabel.setText("ODK Aggregate");
    sourceAddressLabel.setText(conf.getUrl().toString());
  }

  public void readConfiguration(Path path) {
    sourceLabel.setText("Custom ODK Directory");
    sourceAddressLabel.setText(path.toString());
  }

  private void createUIComponents() {
    // TODO: place custom component creation code here
  }

  public JComponent getContainer() {
    return container;
  }

  /**
   * Method generated by IntelliJ IDEA GUI Designer
   * >>> IMPORTANT!! <<<
   * DO NOT edit this method OR call it in your code!
   *
   * @noinspection ALL
   */
  private void $$$setupUI$$$() {
    container = new JPanel();
    container.setLayout(new GridBagLayout());
    actionLabel = new JLabel();
    actionLabel.setText("Pulling data from ");
    GridBagConstraints gbc;
    gbc = new GridBagConstraints();
    gbc.gridx = 0;
    gbc.gridy = 0;
    container.add(actionLabel, gbc);
    final JPanel spacer1 = new JPanel();
    gbc = new GridBagConstraints();
    gbc.gridx = 1;
    gbc.gridy = 0;
    gbc.fill = GridBagConstraints.HORIZONTAL;
    container.add(spacer1, gbc);
    final JPanel spacer2 = new JPanel();
    gbc = new GridBagConstraints();
    gbc.gridx = 0;
    gbc.gridy = 1;
    gbc.fill = GridBagConstraints.VERTICAL;
    container.add(spacer2, gbc);
    sourceLabel = new JLabel();
    sourceLabel.setText("Source");
    gbc = new GridBagConstraints();
    gbc.gridx = 2;
    gbc.gridy = 0;
    gbc.weightx = 1.0;
    gbc.anchor = GridBagConstraints.WEST;
    container.add(sourceLabel, gbc);
    sourceAddressLabel = new JLabel();
    sourceAddressLabel.setText("Source Address");
    gbc = new GridBagConstraints();
    gbc.gridx = 0;
    gbc.gridy = 2;
    gbc.anchor = GridBagConstraints.WEST;
    container.add(sourceAddressLabel, gbc);
    resetButton = new JButton();
    resetButton.setText("Reset");
    gbc = new GridBagConstraints();
    gbc.gridx = 2;
    gbc.gridy = 2;
    gbc.anchor = GridBagConstraints.EAST;
    container.add(resetButton, gbc);
  }

  /**
   * @noinspection ALL
   */
  public JComponent $$$getRootComponent$$$() {
    return container;
  }
}
