package org.opendatakit.briefcase.ui.reused;

import java.awt.GridBagConstraints;
import java.awt.GridBagLayout;
import java.util.function.BiConsumer;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JComponent;
import javax.swing.JLabel;
import javax.swing.JPanel;

@SuppressWarnings("checkstyle:MethodName")
public class SourceConfigurationPanelForm extends JComponent {
  private JComboBox sourceComboBox;
  private JButton configureButton;
  private JPanel container;

  private BiConsumer<String, String> onSuccess;

  public SourceConfigurationPanelForm(BiConsumer<String, String> onSuccess) {
    $$$setupUI$$$();
    this.onSuccess = onSuccess;

    configureButton.addActionListener(__ -> {
      configureButton.setEnabled(false);
      triggerConfigure();
      configureButton.setEnabled(true);
    });
  }

  private void triggerConfigure() {
    AggregateServerConnectionDialog dialog = new AggregateServerConnectionDialog(
        new AggregateServerConnectionDialogForm(),
        aggregateServerConnectionConfiguration -> true,
        null,
        onSuccess);
    dialog.getForm().setVisible(true);
  }

  private void createUIComponents() {
    // TODO: place custom component creation code here
  }

  public JPanel getContainer() {
    return container;
  }

  /**
   * Method generated by IntelliJ IDEA GUI Designer
   * >>> IMPORTANT!! <<<
   * DO NOT edit this method OR call it in your code!
   *
   * @noinspection ALL
   */
  private void $$$setupUI$$$() {
    container = new JPanel();
    container.setLayout(new GridBagLayout());
    final JLabel label1 = new JLabel();
    label1.setText("Pull Data From");
    GridBagConstraints gbc;
    gbc = new GridBagConstraints();
    gbc.gridx = 0;
    gbc.gridy = 0;
    container.add(label1, gbc);
    sourceComboBox = new JComboBox();
    final DefaultComboBoxModel defaultComboBoxModel1 = new DefaultComboBoxModel();
    defaultComboBoxModel1.addElement("Aggregate Server");
    sourceComboBox.setModel(defaultComboBoxModel1);
    gbc = new GridBagConstraints();
    gbc.gridx = 2;
    gbc.gridy = 0;
    gbc.weightx = 1.0;
    gbc.anchor = GridBagConstraints.WEST;
    gbc.fill = GridBagConstraints.HORIZONTAL;
    container.add(sourceComboBox, gbc);
    configureButton = new JButton();
    configureButton.setText("Configure");
    gbc = new GridBagConstraints();
    gbc.gridx = 4;
    gbc.gridy = 0;
    gbc.fill = GridBagConstraints.HORIZONTAL;
    container.add(configureButton, gbc);
    final JPanel spacer1 = new JPanel();
    gbc = new GridBagConstraints();
    gbc.gridx = 1;
    gbc.gridy = 0;
    gbc.fill = GridBagConstraints.HORIZONTAL;
    container.add(spacer1, gbc);
    final JPanel spacer2 = new JPanel();
    gbc = new GridBagConstraints();
    gbc.gridx = 3;
    gbc.gridy = 0;
    gbc.fill = GridBagConstraints.HORIZONTAL;
    container.add(spacer2, gbc);
  }

  /**
   * @noinspection ALL
   */
  public JComponent $$$getRootComponent$$$() {
    return container;
  }

}
